Repository Sigma18Unipd/docs, pull requests merged in 2025-05, with the labels that each got.

#42 ve_20250414
  2-RTB/documentidiprogetto/glossario.typ
  2-RTB/verbali/esterni/ve_20250414_1.1.2.typ
  assets/img/wireframe/List.png
  assets/img/wireframe/Login.png
  assets/img/wireframe/MAINUI.png
Labels: Verbale Esterno

#49 Diario di bordo 2025/05/12
  0-diaridibordo/rtb/ddb_20250512.typ
Labels: Comunicazione

#52 Fix termini ripetuti glossario closes #36
  2-RTB/documentidiprogetto/glossario.typ
  2-RTB/documentidiprogetto/pianodiprogetto_0.4.0.typ
  2-RTB/verbali/interni/vi_20250416_1.0.0.typ
Labels: Documenti, Fix

#54 Stesura verbale interno
  2-RTB/documentidiprogetto/pianodiprogetto_0.4.0.typ
  2-RTB/verbali/interni/vi_20250514_1.0.0.typ
Labels: Verbale Interno

#61 Analisi dei requisiti
  2-RTB/documentidiprogetto/analisideirequisiti_0.11.1.typ
  2-RTB/documentidiprogetto/glossario.typ
  assets/usecasediagrams/UC_14.png
  assets/usecasediagrams/UC_15.png
  assets/usecasediagrams/UC_1_2_3_4.png
  assets/usecasediagrams/UC_28.png
  assets/usecasediagrams/UC_29.png
  assets/usecasediagrams/UC_2_4_5_6_7_8.png
  assets/usecasediagrams/UC_4_10_16.png
  assets/usecasediagrams/UC_4_11_12.png
  assets/usecasediagrams/UC_4_13.png
  assets/usecasediagrams/UC_4_17.png
  assets/usecasediagrams/UC_4_18.png
  assets/usecasediagrams/UC_4_19_20.png
  assets/usecasediagrams/UC_4_21.png
  assets/usecasediagrams/UC_4_22_23_24.png
  assets/usecasediagrams/UC_4_25_26.png
  assets/usecasediagrams/UC_4_6_7_27.png
  assets/usecasediagrams/UC_4_9_10.png
Labels: Documenti
